name: mini_chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  intl_phone_field: ^3.1.0
  otp_text_field: ^1.1.3
  get_storage: ^2.0.3
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  dio: ^4.0.6
  permission_handler: ^10.2.0
  contacts_service: ^0.6.3
  google_fonts: ^3.0.1
  share_plus: ^6.3.0
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  socket_io_client: ^2.0.1
  image_picker: ^0.8.6
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/fonts/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 800
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 700
