// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtpOS_XVusgZ-TM7bgo6p20lPofLByd3Y',
    appId: '1:692441333397:web:53c8f7fe0f5a901ff1259c',
    messagingSenderId: '692441333397',
    projectId: 'mini-chat-bs',
    authDomain: 'mini-chat-bs.firebaseapp.com',
    storageBucket: 'mini-chat-bs.appspot.com',
    measurementId: 'G-MLZMC61ZL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9YFM5inlgDCTG-pon7RLJlTGdiMsTUc',
    appId: '1:692441333397:android:1c41811c74a0bd44f1259c',
    messagingSenderId: '692441333397',
    projectId: 'mini-chat-bs',
    storageBucket: 'mini-chat-bs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRcOK88AprOi2LJDt3mIug3WLv8g1LEyc',
    appId: '1:692441333397:ios:e0e234dcbaf10a3bf1259c',
    messagingSenderId: '692441333397',
    projectId: 'mini-chat-bs',
    storageBucket: 'mini-chat-bs.appspot.com',
    iosClientId: '692441333397-1ramgcduodhplf1t0kn53q6rpidp2kuk.apps.googleusercontent.com',
    iosBundleId: 'com.bs.miniChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRcOK88AprOi2LJDt3mIug3WLv8g1LEyc',
    appId: '1:692441333397:ios:e0e234dcbaf10a3bf1259c',
    messagingSenderId: '692441333397',
    projectId: 'mini-chat-bs',
    storageBucket: 'mini-chat-bs.appspot.com',
    iosClientId: '692441333397-1ramgcduodhplf1t0kn53q6rpidp2kuk.apps.googleusercontent.com',
    iosBundleId: 'com.bs.miniChat',
  );
}
